### ISSUE TITLE
Cost per SNP

### ISSUE THREAD

**Issue by gglinzijie** [btsinn/ISSRseq#7]
Thanks for sharing this wonderful genotyping method. I want to try ISSRseq in a small-scale fish breeding study (300-400 fish, 1000-5000 SNPs).  I know the cost depends on many factors. Could you tell me the rough cost estimate for this method (cost per SNP) presented in your paper? Best regards!

**Comment by ssimon4** [comment]
Thank you for the question and apologies for the delayed response! Based on the manufacturers catalogs for our order list in the Full ISSR Seq Protocol document the cost per individual library was ~$25  and we spent an additional ~$15 per individual for sequencing via 2 × 150 bp Illumina MiSeq (reagent kit v2). 

Across all species datasets we generated 83,344 SNPs and after thinning variants to 1 per locus we were left with 11,165 to analyze. I would estimate our final costs (library prep through sequencing) for the 119 individuals we tested to be around $4,800 at $0.004 per SNP analyzed. There are a lot of places in the ISSRseq protocol where these costs can be further cut (number of primers used, multiplexing PCR reactions, number of individuals on the sequencing run, substituting a different kit ect.). Let us know if you would like any additional cost breakdowns for individual reagents, species we sequenced, or equipment!
